- name: Download K9S for ease of managing K8S
  get_url:
    url: https://github.com/derailed/k9s/releases/download/v0.24.2/k9s_Linux_x86_64.tar.gz
    dest: /tmp/k9s.tar.gz

- name: Extract k9.tar.gz into /usr/bin
  ansible.builtin.unarchive:
    src: /tmp/k9s.tar.gz
    dest: /usr/bin