##################################################
# Install Kubenetes Cluster
# 1 Master 1 Worker
##################################################
---
- hosts: kubernetes_cluster
  become: true
  roles:
    - common
    - docker
  tags:
    - docker

- hosts: master
  become: true
  roles:
    - kubernetes/master
    - cni/calico
    - role: helm
      tags: role-helm
    - role: debug
      tags: role-debug
  tags:
    - kubemaster

- hosts: worker
  become: true
  roles:
    - kubernetes/worker
  pre_tasks:
    - name: Gather facts from kubernetes master
      setup:
      delegate_facts: True
      delegate_to: "{{ item }}"
      with_items: "{{ groups['master'] }}"
  tags:
    - kubeworker

- hosts: nfs_server
  become: true
  roles:
    - nfs-server
  tags:
    - nfs-server