##################################################
# Install Kubenetes Cluster
##################################################
---
- hosts: worker
  become: true
  vars_files:
  - vars/default.yml

  tasks:
  - name: Switch off swap
    command: swapoff -a

  - name: Disable Swap in /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Add br_netfilter module
    modprobe:
      name: br_netfilter
      state: present

  - name: Enable ipv4 forwarding, iptable bridge
    sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_file: /etc/sysctl.d/11-kubernetes.conf
      sysctl_set: yes
      reload: yes
    loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

  - name: Install Device Mapper & LVM2
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - device-mapper-persistent-data
      - lvm2
  
  - name: Add Docker Repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Add Kubernetes Repository
    yum_repository:
      name: Kubernetes
      file: Kubernetes
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      enabled: yes
      gpgcheck: yes

  - name: Install Docker Container Engine
    yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Enable and Run Docker
    systemd:
      name: docker
      enabled: yes
      state: started
  
  - name: Install Kubelet, Kubeadm, Kubectl
    yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - kubelet
      - kubeadm
      - kubectl

  - name: Enable and Run Kubelet
    systemd:
      name: kubelet
      enabled: yes
      state: started

  - name: Setting sebool container_manage_cgroup
    seboolean:
      name: container_manage_cgroup
      state: yes
      persistent: yes

  - name: Enable firewall port 6443 for kubernetes
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
    - 6443/tcp
    - 10250/tcp

  - name: Join Kubernetes Cluster
    shell: |
      kubeadm join {{ kube_master_ip }}:6443 \
            --token {{ kube_master_token }} \
            --discovery-token-unsafe-skip-ca-verification \
            --ignore-preflight-errors all
    register: init_cluster