##################################################
# Install Kubenetes Worker
##################################################
- name: Prepare dependencies
  include_tasks: deps.yaml

- name: Install Kubelet, Kubeadm, Kubectl
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and Run Kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Enable firewall port 6443 for kubernetes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - 10250/tcp
  - 10250/tcp
  - 10251/tcp
  - 10252/tcp
  - 10255/tcp
  - 2379/tcp
  - 2380/tcp
  - 4789/udp
  - 5437/tcp
  - 179/tcp

- name: Add KUBELET_EXTRA_ARGS
  template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet

- name: Join Kubernetes Cluster
  shell: |
    kubeadm join {{ kube_master_ip }}:6443 \
          --token {{ kube_master_token }} \
          --discovery-token-unsafe-skip-ca-verification \
          --ignore-preflight-errors all
  register: init_cluster