##################################################
# Install Kubenetes Worker
##################################################
- name: Prepare dependencies
  include_tasks: deps.yaml

- name: Install Kubelet, Kubeadm, Kubectl
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable and Run Kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Enable firewall port 6443 for kubernetes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - 6443/tcp
  - 10250/tcp

- name: Join Kubernetes Cluster
  shell: |
    kubeadm join {{ kube_master_ip }}:6443 \
          --token {{ kube_master_token }} \
          --discovery-token-unsafe-skip-ca-verification \
          --ignore-preflight-errors all
  register: init_cluster