haproxy_frontend:
  - |
    frontend apiserver
      bind *:6443
      mode tcp
      option tcplog
      default_backend apiserver

haproxy_backend:
  - |
    backend apiserver
      mode tcp
      option ssl-hello-chk
      balance roundrobin
      server master1 10.146.0.11:6443 check fall 3 rise 2
      server master2 10.146.0.12:6443 check fall 3 rise 2
      server master3 10.146.0.13:6443 check fall 3 rise 2