haproxy_frontend:
  - |
    frontend apiserver
      bind *:6443
      mode tcp
      option tcplog
      default_backend apiserver

haproxy_backend:
  - |
    backend apiserver
      option httpchk GET /healthz
      http-check expect status 200
      mode tcp
      option ssl-hello-chk
      balance roundrobin
        server master1 192.168.10.21:6443 check
        server master2 192.168.10.22:6443 check