---
- name: Installing curl, policoreutils, openssh, postfix
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - curl
      - policycoreutils
      - openssh-server
      - openssh-clients
      - postfix

- name: Enable sshd
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: Enable postfix
  systemd:
    name: postfix
    state: started
    enabled: yes