---
# Kubernetes
kubernetes_version: 1.17.0

# Networking
network_service_cidr: "10.96.0.0/12"
network_pod_cidr: "10.10.0.0/16"

# Cluster Info
kube_master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4'].address | default(groups['master'][0]) }}"
kube_master_token: ecpysl.teal08z7ww5ge4t6
kube_master_discovery_token: "sha256:6718a931fb4c3f2ce986c67741f6c4b90bc46324a5b7a0d0bc2150be2749cd0e"