##################################################
# Configure Common Server Setting
##################################################

- name: Switch off swap
  command: swapoff -a

- name: Disable Swap
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disabled /swap on fstab
  replace:
    dest: /etc/fstab
    regexp: '^/swapfile'
    replace: '#/swapfile'

- name: Install nfs-utils
  yum:
    name:
      - nfs-utils
      - libsemanage-python
    state: present