##################################################
# Configure Common Setting
##################################################

- name: Setup
  setup:

- name: Kubernetes master ip address
  debug:
    msg: "{{ inventory_hostname }}"