- hosts: kubernetes_cluster
  become: true
  roles:
    - common_server
    - common_kubernetes
    - docker
  tags:
    - kubebase

- hosts: master
  become: true
  serial: 1
  roles:
    - kubernetes/master
    - role: cni/calico
      tags: kubecali
    - role: helm
      tags: kubehelm
    - role: kubernetes/get_join_info
      tags: getjoininfo
  pre_tasks:
    - name: Gather facts from kubernetes loadbalancer
      setup:
      delegate_facts: True
      delegate_to: "{{ item }}"
      with_items: "{{ groups['haproxy'] }}"
  tags:
    - kubemaster

- hosts: master_worker
  become: true
  roles:
    - kubernetes/master_worker
  tags:
    - kubemasterworker

- hosts: worker
  become: true
  roles:
    - kubernetes/worker
  tags:
    - kubeworker